import AppProvider from "./context";
import "./globals.css";
import Modal from "./Modal";
import "../public/ClashDisplay_Complete/ClashDisplay_Complete/Fonts/WEB/css/clash-display.css";
import ReactQueryProvider from "./ReactQueryProvider";
export const metadata = {
  title: "Dashboard - Admin | My home etal",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/favicon.png",
        href: "/favicon.png",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/favicon.png",
        href: "/favicon.png",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <AppProvider>
          <body className="overflow-x-hidden w-screen ">
            <Modal />
            {children}
          </body>
        </AppProvider>
      </ReactQueryProvider>
    </html>
  );
}
